version: "3.8"

services:
  database:
    container_name: ${CONTAINER_BASENAME}-demo_database
    image: mariadb:focal
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "root",
          "-p$${MYSQL_ROOT_PASSWORD?REQUIRED}",
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: ${CONTAINER_BASENAME}-demo_php
    image: ${TAG}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - assets:/var/www/html/_assets/
      - chevereto:/var/www/html/
    ports:
      - 9000
    restart: always
    healthcheck:
      test: ["CMD", "stat", "/var/CONTAINER_STARTED_PLACEHOLDER"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      CHEVERETO_TAG: ${VERSION}
      CHEVERETO_LICENSE: ${LICENSE}
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HTTPS: 0
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: ${URL_DEMO}_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/_assets/
      CHEVERETO_ENCRYPTION_KEY:

  http:
    container_name: ${CONTAINER_BASENAME}-demo_http
    image: httpd:2.4
    depends_on:
      php:
        condition: service_healthy
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/:ro
      - assets:/var/www/html/_assets/:ro
      - chevereto:/var/www/html/:ro
      - type: bind
        source: ${PWD}/httpd/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
    ports:
      - ${PORT_FLAG_DEMO}${VERSION_PORT}:80
    restart: always

volumes:
  database:
  assets:
  storage:
  chevereto:

networks:
  chevereto:
